server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/blog_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  redis:
    # 连接地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 数据库
    database: 0
    # 用户名，如果有
    # username:
    # 密码，如果有
    # password:
    # 连接超时
    connect-timeout: 5s
    # 读超时
    timeout: 5s

    # Lettuce 客户端的配置
    lettuce:
      # 连接池配置
      pool:
        # 最小空闲连接
        min-idle: 0
        # 最大空闲连接
        max-idle: 8
        # 最大活跃连接
        max-active: 8
        # 从连接池获取连接 最大超时时间，小于等于0则表示不会超时
        max-wait: -1ms

# mybatis-plus
mybatis-plus:
  configuration:
    # 驼峰转小写字母
    map-underscore-to-camel-case: true

#分页器
pagehelper:
  #分页合理化参数默认false，当该参数设置为true 时，pageNum <= 0 时，默认显示第一页，pageNum 超过 pageSize 时，显示最后一页。
  reasonable: true
  # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致
  defaultCount: true
  # 指定数据库，可以不配置，pagehelper插件会自动检测数据库的类型。
  helper-dialect: mysql


